### ISSUE TITLE
wrong check for mmap result

### ISSUE THREAD

**Issue by gocarlos** [jvo203/FITSWebQL#1]
https://github.com/jvo203/FITSWebQL/blob/480095a973db37308d625f46eb7d816e4db4d410/src/main_uWS.cpp#L1164 should check for `MAP_FAILED` not `NULL`

```
    On success, mmap() returns a pointer to the mapped area.  On error,
       the value MAP_FAILED (that is, (void *) -1) is returned, and errno is
       set to indicate the cause of the error.
```

**Comment by jvo203** [comment]
Thank you, will correct the code. Please note this is a new v5 under active development. The current full-featured version is still the v4 coded in Rust.

**Comment by jvo203** [comment]
Fixed this in main_uWS.cpp as well as similar problems in fits.cpp. Thank you for reporting the issue.
